version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: calendar_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calendar_api
    restart: always
    env_file:
      - .env
    ports:
      - "8020:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
