version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: calendar_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calendar_api
    restart: always
    env_file:
      - .env
    ports:
      - "8020:8080"
    depends_on:
      - postgres

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: calendar_swagger
    ports:
      - "8021:8080"
    volumes:
      - ./api/docs/swagger.yml:/swagger.yml
    environment:
      SWAGGER_JSON: /swagger.yml

volumes:
  postgres_data:
